CREATE DATABASE IF NOT EXISTS parking_db;

USE parking_db;

CREATE TABLE IF NOT EXISTS parking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(50) NOT NULL,
    entrada BOOLEAN NOT NULL,
    hora DATETIME NOT NULL
);
